### ISSUE TITLE
[Bug] `CodedAs` causes crash in enum when encoding.

### ISSUE THREAD

**Issue by SouHanaQiao** [SwiftyLab/MetaCodable#72] opened 2024-03-27 09:01 UTC
## `CodedAs` attribute is confusing in enumerations.

``` swift
enum SomeEnum {
    case bool( variable: Bool)
    @CodedAs("altInt")
    case int(val: Int)
    @CodedAs("altDouble1", "altDouble2")
    case double(_: Double)
    case string(String)
    case multi(_ variable: Bool, val: Int, String)
}

try? JSONDecoder().encode(SomeEnum.multi(false, val: 10, "test")) /// will crash
```

``` swift
@Codable
@CodedAt("type")
enum SomeEnum {
    case bool(_ variable: Bool)
    @CodedAs("altInt")
    case int(val: Int)
    @CodedAs("altDouble1", "altDouble2")
    case double(_: Double) /// Crash when encode
    case string(String) /// Crash when encode
    case multi(_ variable: Bool, val: Int, String) /// Crash when encode
}
```
What json to decode with `case double(_: Double)` `case multi(_ variable: Bool, val: Int, String)` ?

**Comment by SouHanaQiao** [comment] 2024-03-27 09:05
I I forgot to add @Codable attribute.

**Comment by SouHanaQiao** [comment] 2024-03-27 09:45
``` swift
/**
 {"altInt":{"val":1}}
 {"altDouble1":0.11}
 {"altDouble2":0.11}
 {"string":"hello"}
 {"multi":{"variable2":"world","variable":true,"val":1}}
 */
@Codable
enum CodedAsTestAtEnum1 {
    case bool( variable: Bool)
    @CodedAs("altInt")
    case int(val: Int)
    @CodedAs("altDouble1", "altDouble2")
    case double(_: Double)
    case string(String)
    case multi(_ variable: Bool, val: Int, _ variable2: String)
    
    static let decodedStrings = [#"{"bool":{"variable":false}}"#, #"{"altInt":{"val":1}}"#, #" {"altDouble1":0.11}"#, #"{"altDouble2":0.11}"#, #" {"string":"hello"}"#, #"{"multi":{"variable2":"world","variable":true,"val":1}}"#]
    
    static func test() throws {
        let decoder = JSONDecoder()
        for jsonString in decodedStrings {
            let result = try decoder.decode(Self.self, from: jsonString)
            print(result)
        }
    }
}

/**
 {"type":"bool","variable":false}
 {"type":"altInt","val":1}
 {"type":"string","string":"hello"}
 {"double":0.11,"type":"altDouble1"}
 {"double":0.11,"type":"altDouble2"}
 {"val":1,"type":"multi","variable":true,"variable2":"world"}
 */
@Codable
@CodedAt("type")
enum CodedAsTestAtEnum2 {
    case bool(_ variable: Bool)
    @CodedAs("altInt")
    case int(val: Int)
    @CodedAs("altDouble1", "altDouble2")
    case double(_ double: Double)
    case string(_ string: String)
    case multi(_ variable: Bool, val: Int, _ variable2: String)
    
    static let decodedStrings = [#"{"type":"bool","variable":false}"#, #" {"type":"altInt","val":1}"#, #"{"double":0.11,"type":"altDouble1"}"#, #"{"double":0.11,"type":"altDouble2"}"#, #"{"type":"string","string":"hello"}"#, #"{"val":1,"type":"multi","variable":true,"variable2":"world"}"#]
    
    static func test() throws {
        let decoder = JSONDecoder()
        for jsonString in decodedStrings {
            let result = try decoder.decode(Self.self, from: jsonString)
            print(result)
        }
    }
}
```
This is right example.

**Comment by soumyamahunt** [comment] 2024-03-27 11:21
@SouHanaQiao please follow the format of the issue template, what did you expect happening and what happens currently?
Please provide reproduction steps if possible.

And have you gone through the `CodedAs` documentation? If yes what part of document was confusing to you?

**Comment by SouHanaQiao** [comment] 2024-03-28 01:43
### > @SouHanaQiao please follow the format of the issue template, what did you expect happening and what happens currently? Please provide reproduction steps if possible.
I just copy test case in `CodedAsEnumTests` file.
I don't know which json decoding is defined for the following enumerations:
 ``` swift
@Codable
enum SomeEnum {
case bool(_ variable: Bool)
@CodedAs("altInt")
case int(val: Int)
@CodedAs("altDouble1", "altDouble2")
case double(_: Double)
case string(String)
case multi(_ variable: Bool, val: Int, String)
}
```
``` swift
@Codable
@CodedAt("type")
enum SomeEnum {
case bool(_ variable: Bool)
@CodedAs("altInt")
case int(val: Int)
@CodedAs("altDouble1", "altDouble2")
case double(_: Double)
case string(String)
case multi(_ variable: Bool, val: Int, String)
}
```

So I'm trying to encode each case so that in turn I can infer the corresponding json. like this:
```
func testEncode() {
    let encoder = JSONEncoder()
    let cases: [SomeEnum] = [.bool(variable: false), .double(0.1), .int(val: 1), .string("hello"), .multi(true, val: 10, "world")]
    do {
        for `case` in cases {
            let data = try encoder.encode(`case`)
            let string = String(data: data, encoding: .utf8)
            print(string)
        }
    } catch {
        print(error)
    }
}
```
Unfortunately this will cause a crash.Are the use cases in the test incorrect, although they can be expanded normally?

**Comment by soumyamahunt** [comment] 2024-03-28 04:27
@SouHanaQiao please refer to [docs](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable) for use-cases. Tests of this library only test expansion not use-cases, it is up to users of this library to design their use-cases.

The enum you are referring to is expected to crash for `double`, `string` and `multi` since all are encoding a single value in a dictionary container (while ideally this should have thrown error, but that is up to Swift Foundation implementation, you can ask Swift Foundation team for reason of crash instead of throwing error).

Closing this issue as it isn't a bug.

**Closed by soumyamahunt** 2024-03-28 04:27 UTC
Labels: question
